### ISSUE TITLE
Would you be open to a pull-request that adds a keys() method

### ISSUE THREAD

**Issue by jimlindeman** [koding/cache#4]
I would like to use this cache, but we have a usecase the current code can't resolve because the cache resource is private in MemoryTTL.  The usecase is where we are storing a <tenant-id>-<date> as the key in the cache, and I have a scenario where I need to walk through the current keys in the cache, and delete any entries that contain a matching tenant-id in the key.  Without having a keys() method, I can't do this because the date field is unknown.

I don't care if the keys list becomes out of date (the query and delete flow doesn't need to be behind a single mutex). Would you be open to a pull request that adds this keys() method that collects the keys from the underlying cache.items map ?

**Comment by cihangir** [comment]
Hi @jimlindeman, Thanks for opening an issue before sending a PR

Do you have a fixed place for your tenant-id? (as prefix or suffix) If you have a similar architecture you can use the tenant id while constructing caches on the fly and assign the values to the `sharded` cache, by this way you could eliminate the need for a `Keys()` method.

I think a simple code could explain better

```
package cache

type ShardedNoTS struct {
	cache       map[string]Cache
	itemCount   map[string]int
	constructor func() Cache
}

func NewShardedNoTS(c func() Cache) *ShardedNoTS {
	return &ShardedNoTS{
		constructor: c,
		cache:       make(map[string]Cache),
		itemCount:   make(map[string]int),
	}
}

func (l *ShardedNoTS) Get(tenantId, key string) (interface{}, error) {
	cache, ok := l.cache[tenantId]
	if !ok {
		return nil, ErrNotFound
	}

	return cache.Get(key)
}

func (l *ShardedNoTS) Set(tenantId, key string, val interface{}) error {
	_, ok := l.cache[tenantId]
	if !ok {
		l.cache[tenantId] = l.constructor()
		l.itemCount[tenantId] = 0
	}

	l.itemCount[tenantId]++
	return l.cache[tenantId].Set(key, val)
}

func (l *ShardedNoTS) Delete(tenantId, key string) error {
	_, ok := l.cache[tenantId]
	if !ok {
		return nil
	}

	l.itemCount[tenantId]--

	if l.itemCount[tenantId] == 0 {
		return l.DeleteShard(tenantId)
	}

	return l.cache[tenantId].Delete(key)
}

func (l *ShardedNoTS) DeleteShard(tenantId string) error {
	delete(l.cache, tenantId)
	delete(l.itemCount, tenantId)

	return nil
}

```


This does not satisfy the `Cache` interface but just wanted to give the idea. If interface is important for you, you can pass a delimiter in the constructor of `ShardedNoTS` and split the tenant id and the key in the interface function implementations while satisfying the interface
smth like http://play.golang.org/p/FtMVzmY8AC

**Comment by jimlindeman** [comment]
The problem is that we have an indeterminate # of tenants when we scale to production (1 to 30000+), what you described above would just create leftovers with the l.cache[tenantId] when a tenant no longer uses the system (i.e. need a TTL on that layer too) and hundreds of GC threads needing to be run.    That's why I'd prefer to just keep one cache layer with a single GC thread and just be able to query the current keys in the cache.

**Comment by jimlindeman** [comment]
Just realized if the GC method just iterated all the tenant indexed caches and used the regular Delete method, that should cleanup the cache fine with a single GC thread.  I'd probably have to make one with the TTL logic like MemoryTTL too.

**Comment by cihangir** [comment]
So if understand you correctly, you want to modify `StartGC` function. I would be open to change the signature of it
```func (r *MemoryTTL) StartGC(gcInterval time.Duration) {```

to 

```
type TTLFilter func(key string) bool
func (r *MemoryTTL) StartGC(gcInterval time.Duration, filters ...TTLFilter) {
// if len(filters) is 0 then set filters[0] to isValid
```

So we will be bakward compatible, wont add anything to interface and your problem will be solved.

What do you think?

**Comment by jimlindeman** [comment]
I ended up taking your original code sniplet and building a basic ShardedNoTS class with it, and then building a ShardedTTL class on top of it similar to how you built MemoryTTL on top of MemoryNoTS.  The GC method only had to be in the higher level ShardedTTL class, and I was able to let that layer manage iteration of keys for GC and DeleteShard methods, as it could iterate the keys from its setAts structure:
// setAts holds the time that related item's set at, indexed by tenantId
setAts map[string]map[string]time.Time

I would just check it in and point you to it as I think it follows your original design, but I need to get management approval before putting it out there.

**Comment by cihangir** [comment]
Ok thanks for the update @jimlindeman

**Comment by jimlindeman** [comment]
Sorry for the long delay, but I finally got the approval to give our sharded cache changes back.  The changes can be viewed at https://github.com/jimlindeman/cache/commit/17fd0d68bdba6bde58d127052afbed179e528f1d .  I can create a PR if you're interested.

**Comment by cihangir** [comment]
Hi @jimlindeman Yes i would like to see your changes in this repo. I have small comments on some parts, we can talk about them when you open the PR.

**Comment by cihangir** [comment]
fixed with https://github.com/koding/cache/pull/5
