### ISSUE TITLE
Reuse time.Now() result in StartGC()

### ISSUE THREAD

**Issue by ash2k** [koding/cache#7]
`StartGC()` in both `MemoryTTL` and `ShardedTTL` can be optimized to only call `time.Now()` once and pass the result to `r.isValid()`. For huge caches it may save a lot of overhead. Actually it can also avoid the overhead of adding a TTL to the item's setAt by subtracting `r.ttl` from the current time.
```go
deadline := time.Now().Add(-r.ttl)
// ...
return setAt.After(deadline)
```

**Comment by cihangir** [comment]
fixed with https://github.com/koding/cache/pull/9 Thanks for the suggestion @ash2k
